version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: tchonbet-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: tchonbet
    ports:
      - 5432:5432
    networks:
      - tchonbet-network

networks:
  tchonbet-network:
    driver: bridge
